Added `Remove-RegistryKey` to RegistryHelpers
dkbrookie/PowershellFunctions pull request #14
Opened 2022-01-20 22:22 UTC by sethbrasile

And updated documentation for new function.

2022-01-21 14:52 UTC, wmmatt requested changes
I think you can remove that if `$null` check, see whatcha think.

2022-01-21 14:52 UTC, wmmatt commented on Function.Registry-Helpers.ps1
> +    }
Since you've made `$Path` Mandatory you'd never have a `$null` here ;)

2022-01-21 20:20 UTC, sethbrasile commented
Need to make sure input is actually a string, probably need to regex it to make sure it's a valid registry path.

Right now, this function could accidentally nuke a folder if accidentally fed a word that happens to be a folder in the current working directory.

2022-01-21 22:10 UTC, sethbrasile commented on Function.Registry-Helpers.ps1
> +    }
I believe this is handled by the more thorough check I added via regex. Ready for review again.

2022-01-24 15:10 UTC, wmmatt approved these changes
I am putting approved because I've gone through this and haven't been able to cripple my test VM but just a reminder that remove anything functions are VERY sensitive, and registry removals are even more sensitive. I get that's part of the justification for making the process repeatable but you get me...please test test test before in full prod.

2022-01-24 15:10 UTC, wmmatt commented on Function.Registry-Helpers.ps1
> +    $regex = '^HKLM:\\([a-zA-Z0-9\s_@\-\^!#.\:\/\$%&+={}\[\]\\*])+$'
Tested this out a bunch and I couldn't break it so should be good. I saw your note on only HKLM and I can't really think of a time where you really need another registry path other than like HKU but even that is super niche so this should be fine.

2022-01-24 16:39 UTC, merged